services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      environment:
        MINIO_ENDPOINT: http://localhost:9000
        MINIO_ROOT_USER: minio99  
        MINIO_ROOT_PASSWORD: minio123

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
    command: server /data --console-address ":9001"

volumes:
  minio_data:
